### ISSUE TITLE
Using JointJS with Browserify

### ISSUE THREAD

**Issue by andyperlitch** [DavidDurman/joint#50]
Love the library, hoping to use it with my current architecture which uses Browserify, however I'm finding it difficult to accomplish. An example is that `index.js` does not include Paper in the exported object.

Is there something I am missing? Is there are particular way to use JointJS with Browserify?

Thanks in advance!
Andy

**Comment by serapath** [comment]
I just tried to install `npm install jointjs` and it gives me outdated version 0.8 which doesnt even work properly when i browserify and require it.
Then i tried with installing directly from github, but that fails too.

In `package.json` there should be a `main` property that tells where to enter the library.
There are a lot of files in that project and i tried now to `require('jointjs/dist/joint`) but even that fails because paths are wrong.

There is actually an `index.js` in the project root which seems to be there just for browserify, but its missing some stuff, because i cannot follow this [demo](http://www.jointjs.com/demos/fsa) example because it cannot find `joint.dia.paper`.

It would be easy to fix if i would know what is all the stuff that is supposed to be on the `joint` object.

**Comment by serapath** [comment]
See #115

**Comment by chill117** [comment]
Browserify support added by PR #135, which has been merged.
